Feature/homework7
MashaChornaya/HerokuApp_Mahsa_Chornaya pull request #2
Opened 2022-07-05 17:12 UTC by MashaChornaya

2022-07-06 16:46 UTC, voropa requested changes

2022-07-06 16:46 UTC, voropa commented on TestPage.html
> +<!DOCTYPE html>
Please correct all warnings
**
<img width="330" alt="image" src="https://user-images.githubusercontent.com/14195681/177601945-a284170a-5dbb-4abc-b6dc-9f1a100e46bf.png">
**

2022-07-07 19:25 UTC, MashaChornaya commented on TestPage.html
> +<!DOCTYPE html>
fixed all

2022-08-02 18:50 UTC, voropa approved these changes

2022-08-14 19:12 UTC, merged